scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.3
    upper_threshold: 5
    lower_replacement_value: -.inf
    upper_replacement_value: .inf
- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 0
    max_range: 5.0
    max_range_difference: 0.1
    filter_window: 20
